knp_paginator:
    page_range: 5                      # Nombre de liens affichés dans le menu de pagination
    default_options:
        page_name: page                # Nom du paramètre de requête pour la page
        sort_field_name: sort          # Nom du paramètre pour le tri
        sort_direction_name: direction # Nom du paramètre pour la direction du tri
        distinct: true                 # Résultats distincts (utile pour les GROUP BY)
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'  # Template Bootstrap 4
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'