framework:
    notifier:
        channel_policy:
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        
        admin_recipients:
            - email: haifacheikh27@gmail.com
              phone: '+21624826754'
        
        # Remplacez 'transports' par 'chatter_transports' et 'texter_transports'
        chatter_transports:
            mercure: '%env(MERCURE_DSN)%'
            email: '%env(MAILER_DSN)%'