security:
    # Configuration des encodeurs de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # Fournisseurs d'utilisateurs
    providers:
        users_in_memory:
            memory: null
    
    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: users_in_memory
            security: false  # Désactive complètement l'authentification
    
    # Contrôle d'accès
    access_control:
        - { path: ^/reservation/new, roles: PUBLIC_ACCESS }
        - { path: ^/reservation/\d+$, roles: PUBLIC_ACCESS }
        - { path: ^/reservation/\d+/edit, roles: PUBLIC_ACCESS }
        - { path: ^/reservation/\d+/delete, roles: PUBLIC_ACCESS }
        - { path: ^/reservation/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10