controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
reservation_stats:
    path: /reservations/statistiques
    controller: App\Controller\ReservationController::statistics
app_trip_map:
    path: /trip/{id}/map
    controller: App\Controller\TripController::showMap
app_reservation_qrcode:
    path: /reservation/qrcode/{id}
    controller: App\Controller\QrCodeController::generateQrCode
    methods: GET

app_reservation_validate:
    path: /reservation/validate/{id}
    controller: App\Controller\QrCodeController::validateReservation
    methods: GET