controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
reservation_stats:
    path: /reservations/statistiques
    controller: App\Controller\ReservationController::statistics
app_trip_qrcode:
    path: /trip/{id}/qrcode
    controller: App\Controller\TripController::generateQrCode

app_trip_map:
    path: /trip/{id}/map
    controller: App\Controller\TripController::showMap
    