controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
reservation_stats:
    path: /reservations/statistiques
    controller: App\Controller\ReservationController::statistics
    