parameters:
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_from_number: '%env(TWILIO_FROM_NUMBER)%'
    test_phone_number: '%env(TEST_PHONE_NUMBER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\TwilioSmsService:
        arguments:
            $params: '@parameter_bag'
            $logger: '@logger'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'