app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

app_login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [GET, POST]

api_login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: POST

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    methods: POST